[build]
  publish = "www"
  command = "npm run build"

# REDIRECT and HEADERS examples

# Redirect rule example
# For more information see:- https://www.netlify.com/docs/netlify-toml-reference/

#[[redirects]]
#  from = "/*"
#  to = "/blog/:splat"

# The default HTTP status code is 301, but you can define a different one e.g.
# status = 302

# Headers rule example
# For more information see:- https://www.netlify.com/docs/netlify-toml-reference/

[[headers]]
  for = "/assets/fonts/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://minamarkh.am"
